{{ if eq .Values.portalScope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: litmus-server
  namespace:  {{ .Values.portalNamespace }}
  labels:
    name: litmus-server
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
{{ end }}